"""empty message

Revision ID: 065fe196732f
Revises: 8b49d9e1f9f2
Create Date: 2017-09-01 00:49:18.081092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '065fe196732f'
down_revision = '8b49d9e1f9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.drop_constraint('tournament_ibfk_2', 'tournament', type_='foreignkey')
    op.create_foreign_key(None, 'tournament', 'user', ['organizer_id'], ['id'])
    op.drop_column('tournament', 'organizer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('organizer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.create_foreign_key('tournament_ibfk_2', 'tournament', 'user', ['organizer'], ['id'])
    op.drop_column('tournament', 'organizer_id')
    # ### end Alembic commands ###
