"""empty message

Revision ID: 1a94ce81ade0
Revises: b3a8cbcd54f9
Create Date: 2017-09-01 01:04:35.372802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a94ce81ade0'
down_revision = 'b3a8cbcd54f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('judge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament', 'judge', ['judge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'judge_id')
    # ### end Alembic commands ###
