"""empty message

Revision ID: 2354747979b6
Revises: b59d547748a1
Create Date: 2017-12-13 16:14:29.617977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2354747979b6'
down_revision = 'b59d547748a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('number_of_teams', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'number_of_teams')
    # ### end Alembic commands ###
