"""empty message

Revision ID: 412706a57a5a
Revises: 065fe196732f
Create Date: 2017-09-01 01:02:10.067187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '412706a57a5a'
down_revision = '065fe196732f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournament_ibfk_1', 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'organizer_id')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'tournament')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tournament', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'tournament', ['tournament'], ['id'])
    op.add_column('tournament', sa.Column('organizer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tournament_ibfk_1', 'tournament', 'user', ['organizer_id'], ['id'])
    # ### end Alembic commands ###
