"""empty message

Revision ID: 57d8399e361a
Revises: 0d8469473d50
Create Date: 2017-10-07 17:25:19.882709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d8399e361a'
down_revision = '0d8469473d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('score', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'score')
    # ### end Alembic commands ###
