"""empty message

Revision ID: 689bc38313a4
Revises: 1a94ce81ade0
Create Date: 2017-09-01 01:08:15.952732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689bc38313a4'
down_revision = '1a94ce81ade0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captain', sa.Column('tournament', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'captain', 'tournament', ['tournament'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'captain', type_='foreignkey')
    op.drop_column('captain', 'tournament')
    # ### end Alembic commands ###
