"""empty message

Revision ID: 8b49d9e1f9f2
Revises: 63619a75816e
Create Date: 2017-09-01 00:42:59.460293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b49d9e1f9f2'
down_revision = '63619a75816e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournament_ibfk_1', 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'judge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('judge', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tournament_ibfk_1', 'tournament', 'user', ['judge'], ['id'])
    # ### end Alembic commands ###
