"""empty message

Revision ID: 90dd2bd37de8
Revises: 57d8399e361a
Create Date: 2017-10-07 17:34:55.120702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90dd2bd37de8'
down_revision = '57d8399e361a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'score')
    op.drop_column('team', 'total_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('total_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('member', sa.Column('score', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    # ### end Alembic commands ###
