"""empty message

Revision ID: a5785225ec86
Revises: fa947be14599
Create Date: 2017-12-09 20:44:26.275618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5785225ec86'
down_revision = 'fa947be14599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pair', sa.Column('cap0_score', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.add_column('pair', sa.Column('cap1_score', sa.DECIMAL(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pair', 'cap1_score')
    op.drop_column('pair', 'cap0_score')
    # ### end Alembic commands ###
