"""empty message

Revision ID: b3a8cbcd54f9
Revises: 412706a57a5a
Create Date: 2017-09-01 01:03:30.245545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a8cbcd54f9'
down_revision = '412706a57a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament', 'organizer', ['organizer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'organizer_id')
    # ### end Alembic commands ###
