"""empty message

Revision ID: b59d547748a1
Revises: a5785225ec86
Create Date: 2017-12-10 14:19:49.852851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59d547748a1'
down_revision = 'a5785225ec86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('assessed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'assessed')
    # ### end Alembic commands ###
