"""empty message

Revision ID: bdec20612c45
Revises: d5965da89905
Create Date: 2017-12-09 18:38:14.083337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdec20612c45'
down_revision = 'd5965da89905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pair', sa.Column('assessed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pair', 'assessed')
    # ### end Alembic commands ###
