"""empty message

Revision ID: c7f173f1484d
Revises: 97e4219f7f56
Create Date: 2017-09-02 02:43:37.761300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f173f1484d'
down_revision = '97e4219f7f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'name')
    # ### end Alembic commands ###
