"""empty message

Revision ID: cfe4e2a41e72
Revises: 90dd2bd37de8
Create Date: 2017-10-07 18:01:47.659019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe4e2a41e72'
down_revision = '90dd2bd37de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('score', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.add_column('team', sa.Column('total_score', sa.DECIMAL(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'total_score')
    op.drop_column('member', 'score')
    # ### end Alembic commands ###
