"""empty message

Revision ID: dab0ada097df
Revises: 091dd80c4b2b
Create Date: 2017-09-01 00:18:55.505533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab0ada097df'
down_revision = '091dd80c4b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tournament', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'tournament', ['tournament'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tournament')
    # ### end Alembic commands ###
