"""empty message

Revision ID: fa947be14599
Revises: bdec20612c45
Create Date: 2017-12-09 19:53:47.185603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa947be14599'
down_revision = 'bdec20612c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('current_round', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'current_round')
    # ### end Alembic commands ###
